export interface SectionMapping {
  ipcSection: string;
  ipcTitle: string;
  bnsSection: string;
  bnsTitle: string;
  changes: string;
  category: string;
}

export const ipcToBnsMappings: SectionMapping[] = [
  // --- Offences Against Body ---
  {
    ipcSection: "299",
    ipcTitle: "Culpable homicide",
    bnsSection: "100",
    bnsTitle: "Culpable homicide",
    changes: "No substantive change. Language simplified.",
    category: "Offences Against Body",
  },
  {
    ipcSection: "300",
    ipcTitle: "Murder",
    bnsSection: "101",
    bnsTitle: "Murder",
    changes: "No substantive change. Same 4 clauses retained.",
    category: "Offences Against Body",
  },
  {
    ipcSection: "302",
    ipcTitle: "Punishment for murder",
    bnsSection: "103",
    bnsTitle: "Punishment for murder",
    changes: "Death penalty or life imprisonment retained. NEW: Mob lynching added — where a group of 5+ persons commits murder on grounds of race, caste, community, sex, language, or personal belief, each member punishable with death or life imprisonment + fine.",
    category: "Offences Against Body",
  },
  {
    ipcSection: "304",
    ipcTitle: "Culpable homicide not amounting to murder",
    bnsSection: "105",
    bnsTitle: "Culpable homicide not amounting to murder",
    changes: "No substantive change.",
    category: "Offences Against Body",
  },
  {
    ipcSection: "304A",
    ipcTitle: "Death by negligence",
    bnsSection: "106",
    bnsTitle: "Death by negligence",
    changes: "NEW: Enhanced punishment for death caused by rash/negligent driving — imprisonment up to 7 years + fine. If offender flees without reporting, up to 10 years.",
    category: "Offences Against Body",
  },
  {
    ipcSection: "304B",
    ipcTitle: "Dowry death",
    bnsSection: "80",
    bnsTitle: "Dowry death",
    changes: "No substantive change. Moved to chapter on offences against women.",
    category: "Offences Against Women",
  },
  {
    ipcSection: "306",
    ipcTitle: "Abetment of suicide",
    bnsSection: "108",
    bnsTitle: "Abetment of suicide",
    changes: "No substantive change.",
    category: "Offences Against Body",
  },
  {
    ipcSection: "307",
    ipcTitle: "Attempt to murder",
    bnsSection: "109",
    bnsTitle: "Attempt to murder",
    changes: "No substantive change.",
    category: "Offences Against Body",
  },
  {
    ipcSection: "319",
    ipcTitle: "Hurt",
    bnsSection: "114",
    bnsTitle: "Hurt",
    changes: "No substantive change.",
    category: "Offences Against Body",
  },
  {
    ipcSection: "320",
    ipcTitle: "Grievous hurt",
    bnsSection: "115",
    bnsTitle: "Grievous hurt",
    changes: "No substantive change.",
    category: "Offences Against Body",
  },
  {
    ipcSection: "323",
    ipcTitle: "Voluntarily causing hurt",
    bnsSection: "118",
    bnsTitle: "Voluntarily causing hurt",
    changes: "Community service added as alternative punishment.",
    category: "Offences Against Body",
  },
  {
    ipcSection: "325",
    ipcTitle: "Voluntarily causing grievous hurt",
    bnsSection: "117",
    bnsTitle: "Voluntarily causing grievous hurt",
    changes: "No substantive change.",
    category: "Offences Against Body",
  },
  {
    ipcSection: "326",
    ipcTitle: "Grievous hurt by dangerous weapons",
    bnsSection: "118",
    bnsTitle: "Grievous hurt by dangerous weapons or means",
    changes: "No substantive change.",
    category: "Offences Against Body",
  },

  // --- Offences Against Women ---
  {
    ipcSection: "354",
    ipcTitle: "Assault or criminal force to woman with intent to outrage modesty",
    bnsSection: "74",
    bnsTitle: "Assault or criminal force to woman with intent to outrage modesty",
    changes: "No substantive change.",
    category: "Offences Against Women",
  },
  {
    ipcSection: "354A",
    ipcTitle: "Sexual harassment",
    bnsSection: "75",
    bnsTitle: "Sexual harassment",
    changes: "No substantive change.",
    category: "Offences Against Women",
  },
  {
    ipcSection: "354D",
    ipcTitle: "Stalking",
    bnsSection: "78",
    bnsTitle: "Stalking",
    changes: "No substantive change.",
    category: "Offences Against Women",
  },
  {
    ipcSection: "375",
    ipcTitle: "Rape",
    bnsSection: "63",
    bnsTitle: "Rape",
    changes: "No substantive change in definition. Marital rape exception retained for wife above 18 years.",
    category: "Offences Against Women",
  },
  {
    ipcSection: "376",
    ipcTitle: "Punishment for rape",
    bnsSection: "64",
    bnsTitle: "Punishment for rape",
    changes: "Minimum 10 years RI retained. NEW: Rape of woman under 18 — minimum 20 years, extendable to life. Gang rape of minor — death penalty or life imprisonment.",
    category: "Offences Against Women",
  },
  {
    ipcSection: "498A",
    ipcTitle: "Cruelty by husband or relatives",
    bnsSection: "85",
    bnsTitle: "Cruelty by husband or relatives",
    changes: "No substantive change.",
    category: "Offences Against Women",
  },

  // --- Property Offences ---
  {
    ipcSection: "378",
    ipcTitle: "Theft",
    bnsSection: "303",
    bnsTitle: "Theft",
    changes: "No substantive change.",
    category: "Property Offences",
  },
  {
    ipcSection: "379",
    ipcTitle: "Punishment for theft",
    bnsSection: "303",
    bnsTitle: "Punishment for theft",
    changes: "Up to 3 years + fine retained.",
    category: "Property Offences",
  },
  {
    ipcSection: "380",
    ipcTitle: "Theft in dwelling house",
    bnsSection: "305",
    bnsTitle: "Theft in dwelling house",
    changes: "Up to 7 years + fine retained.",
    category: "Property Offences",
  },
  {
    ipcSection: "383",
    ipcTitle: "Extortion",
    bnsSection: "308",
    bnsTitle: "Extortion",
    changes: "No substantive change.",
    category: "Property Offences",
  },
  {
    ipcSection: "390",
    ipcTitle: "Robbery",
    bnsSection: "309",
    bnsTitle: "Robbery",
    changes: "No substantive change.",
    category: "Property Offences",
  },
  {
    ipcSection: "392",
    ipcTitle: "Punishment for robbery",
    bnsSection: "309",
    bnsTitle: "Punishment for robbery",
    changes: "RI up to 10 years + fine retained.",
    category: "Property Offences",
  },
  {
    ipcSection: "395",
    ipcTitle: "Dacoity",
    bnsSection: "310",
    bnsTitle: "Dacoity",
    changes: "No substantive change.",
    category: "Property Offences",
  },
  {
    ipcSection: "403",
    ipcTitle: "Dishonest misappropriation of property",
    bnsSection: "314",
    bnsTitle: "Dishonest misappropriation of property",
    changes: "No substantive change.",
    category: "Property Offences",
  },
  {
    ipcSection: "405",
    ipcTitle: "Criminal breach of trust",
    bnsSection: "316",
    bnsTitle: "Criminal breach of trust",
    changes: "No substantive change.",
    category: "Property Offences",
  },
  {
    ipcSection: "406",
    ipcTitle: "Punishment for criminal breach of trust",
    bnsSection: "316",
    bnsTitle: "Punishment for criminal breach of trust",
    changes: "Up to 3 years or fine or both — retained.",
    category: "Property Offences",
  },
  {
    ipcSection: "415",
    ipcTitle: "Cheating",
    bnsSection: "318",
    bnsTitle: "Cheating",
    changes: "No substantive change.",
    category: "Property Offences",
  },
  {
    ipcSection: "420",
    ipcTitle: "Cheating and dishonestly inducing delivery of property",
    bnsSection: "318",
    bnsTitle: "Cheating and dishonestly inducing delivery of property",
    changes: "Up to 7 years + fine retained.",
    category: "Property Offences",
  },
  {
    ipcSection: "425",
    ipcTitle: "Mischief",
    bnsSection: "324",
    bnsTitle: "Mischief",
    changes: "No substantive change.",
    category: "Property Offences",
  },
  {
    ipcSection: "426",
    ipcTitle: "Punishment for mischief",
    bnsSection: "324",
    bnsTitle: "Punishment for mischief",
    changes: "Up to 3 months or fine or both retained.",
    category: "Property Offences",
  },
  {
    ipcSection: "441",
    ipcTitle: "Criminal trespass",
    bnsSection: "329",
    bnsTitle: "Criminal trespass",
    changes: "No substantive change.",
    category: "Property Offences",
  },
  {
    ipcSection: "447",
    ipcTitle: "Punishment for criminal trespass",
    bnsSection: "329",
    bnsTitle: "Punishment for criminal trespass",
    changes: "Up to 3 months or fine up to ₹5,000 or both retained.",
    category: "Property Offences",
  },

  // --- Document & Public Offences ---
  {
    ipcSection: "463",
    ipcTitle: "Forgery",
    bnsSection: "336",
    bnsTitle: "Forgery",
    changes: "No substantive change.",
    category: "Document Offences",
  },
  {
    ipcSection: "465",
    ipcTitle: "Punishment for forgery",
    bnsSection: "336",
    bnsTitle: "Punishment for forgery",
    changes: "Up to 2 years or fine or both retained.",
    category: "Document Offences",
  },
  {
    ipcSection: "468",
    ipcTitle: "Forgery for purpose of cheating",
    bnsSection: "338",
    bnsTitle: "Forgery for purpose of cheating",
    changes: "Up to 7 years + fine retained.",
    category: "Document Offences",
  },
  {
    ipcSection: "471",
    ipcTitle: "Using forged document as genuine",
    bnsSection: "340",
    bnsTitle: "Using forged document or electronic record as genuine",
    changes: "Electronic records explicitly included.",
    category: "Document Offences",
  },

  // --- Offences Against State/Public Tranquility ---
  {
    ipcSection: "120B",
    ipcTitle: "Criminal conspiracy",
    bnsSection: "61",
    bnsTitle: "Criminal conspiracy",
    changes: "No substantive change.",
    category: "General Offences",
  },
  {
    ipcSection: "124A",
    ipcTitle: "Sedition",
    bnsSection: "152",
    bnsTitle: "Acts endangering sovereignty, unity and integrity of India",
    changes: "MAJOR CHANGE: 'Sedition' replaced entirely. New section covers acts that endanger sovereignty/unity through words, signs, electronic communication, or financial means. Punishment: up to 7 years or life imprisonment + fine.",
    category: "Offences Against State",
  },
  {
    ipcSection: "141",
    ipcTitle: "Unlawful assembly",
    bnsSection: "189",
    bnsTitle: "Unlawful assembly",
    changes: "No substantive change.",
    category: "Public Tranquility",
  },
  {
    ipcSection: "147",
    ipcTitle: "Rioting",
    bnsSection: "191",
    bnsTitle: "Rioting",
    changes: "No substantive change.",
    category: "Public Tranquility",
  },
  {
    ipcSection: "153A",
    ipcTitle: "Promoting enmity between groups",
    bnsSection: "196",
    bnsTitle: "Promoting enmity between groups",
    changes: "Expanded to include electronic and social media communication.",
    category: "Public Tranquility",
  },

  // --- Other Important Sections ---
  {
    ipcSection: "34",
    ipcTitle: "Common intention",
    bnsSection: "3(5)",
    bnsTitle: "Common intention",
    changes: "No substantive change. Moved to general explanations chapter.",
    category: "General Principles",
  },
  {
    ipcSection: "107",
    ipcTitle: "Abetment of a thing",
    bnsSection: "45",
    bnsTitle: "Abetment of a thing",
    changes: "No substantive change.",
    category: "General Principles",
  },
  {
    ipcSection: "149",
    ipcTitle: "Common object",
    bnsSection: "190",
    bnsTitle: "Common object",
    changes: "No substantive change.",
    category: "General Principles",
  },
  {
    ipcSection: "170",
    ipcTitle: "Personating a public servant",
    bnsSection: "204",
    bnsTitle: "Personating a public servant",
    changes: "No substantive change.",
    category: "Public Servants",
  },
  {
    ipcSection: "186",
    ipcTitle: "Obstructing public servant in discharge of duty",
    bnsSection: "221",
    bnsTitle: "Obstructing public servant in discharge of duty",
    changes: "No substantive change.",
    category: "Public Servants",
  },
  {
    ipcSection: "279",
    ipcTitle: "Rash driving or riding on public way",
    bnsSection: "281",
    bnsTitle: "Rash driving or riding on public way",
    changes: "No substantive change.",
    category: "Public Safety",
  },
  {
    ipcSection: "294",
    ipcTitle: "Obscene acts and songs",
    bnsSection: "296",
    bnsTitle: "Obscene acts and songs",
    changes: "No substantive change.",
    category: "Public Decency",
  },
  {
    ipcSection: "338",
    ipcTitle: "Causing grievous hurt by act endangering life",
    bnsSection: "125",
    bnsTitle: "Causing grievous hurt by act endangering life",
    changes: "No substantive change.",
    category: "Offences Against Body",
  },
  {
    ipcSection: "499",
    ipcTitle: "Defamation",
    bnsSection: "356",
    bnsTitle: "Defamation",
    changes: "No substantive change. Same 10 exceptions retained.",
    category: "Defamation",
  },
  {
    ipcSection: "500",
    ipcTitle: "Punishment for defamation",
    bnsSection: "356",
    bnsTitle: "Punishment for defamation",
    changes: "Up to 2 years or fine or both retained. Community service added as additional punishment option.",
    category: "Defamation",
  },
  {
    ipcSection: "503",
    ipcTitle: "Criminal intimidation",
    bnsSection: "351",
    bnsTitle: "Criminal intimidation",
    changes: "No substantive change.",
    category: "Criminal Intimidation",
  },
  {
    ipcSection: "506",
    ipcTitle: "Punishment for criminal intimidation",
    bnsSection: "351",
    bnsTitle: "Punishment for criminal intimidation",
    changes: "Up to 2 years or fine or both retained. Aggravated form up to 7 years.",
    category: "Criminal Intimidation",
  },
  {
    ipcSection: "509",
    ipcTitle: "Word, gesture or act intended to insult modesty of woman",
    bnsSection: "79",
    bnsTitle: "Word, gesture or act intended to insult modesty of woman",
    changes: "No substantive change.",
    category: "Offences Against Women",
  },

  // --- NEW OFFENCES in BNS (no IPC equivalent) ---
  {
    ipcSection: "NEW",
    ipcTitle: "No equivalent in IPC",
    bnsSection: "69",
    bnsTitle: "Sexual intercourse by deceitful means or false promise of marriage",
    changes: "ENTIRELY NEW: Sexual intercourse by employing deceitful means or making a false promise of marriage not intended to be fulfilled. Punishment: up to 10 years + fine.",
    category: "New Offences in BNS",
  },
  {
    ipcSection: "NEW",
    ipcTitle: "No equivalent in IPC",
    bnsSection: "111",
    bnsTitle: "Organised crime",
    changes: "ENTIRELY NEW: Defines and punishes organised crime including kidnapping, extortion, land grabbing, contract killing, cyber-crime by a syndicate. Punishment: death or life imprisonment + fine not less than ₹10 lakhs.",
    category: "New Offences in BNS",
  },
  {
    ipcSection: "NEW",
    ipcTitle: "No equivalent in IPC",
    bnsSection: "112",
    bnsTitle: "Petty organised crime",
    changes: "ENTIRELY NEW: Covers pick-pocketing, snatching, theft by organised groups. Punishment: 1–7 years + fine.",
    category: "New Offences in BNS",
  },
  {
    ipcSection: "NEW",
    ipcTitle: "No equivalent in IPC",
    bnsSection: "113",
    bnsTitle: "Terrorist act",
    changes: "ENTIRELY NEW: Comprehensive definition of terrorist acts. Punishment: death or life imprisonment + fine. Conspiracy/attempt also punishable.",
    category: "New Offences in BNS",
  },
];

export function getMappingSummary(): string {
  const categories = [...new Set(ipcToBnsMappings.map((m) => m.category))];
  return categories
    .map((cat) => {
      const items = ipcToBnsMappings.filter((m) => m.category === cat);
      const lines = items
        .map(
          (m) =>
            `  IPC ${m.ipcSection} (${m.ipcTitle}) → BNS ${m.bnsSection} (${m.bnsTitle})${m.changes !== "No substantive change." ? ` | Changes: ${m.changes}` : ""}`
        )
        .join("\n");
      return `**${cat}:**\n${lines}`;
    })
    .join("\n\n");
}
