import jsPDF from "jspdf";
import type { FirmProfile } from "./types/firm";

const DEFAULT_FIRM_NAME = "NAIR & ASSOCIATES";
const DEFAULT_FIRM_TAGLINE = "Advocates & Legal Consultants";
const DEFAULT_FIRM_ADDRESS =
  "3rd Floor, Legal Chambers, MG Road, Ernakulam, Kerala - 682011";
const DEFAULT_FIRM_CONTACT =
  "Phone: +91 484 2345678 | Email: office@nairassociates.in";
const BRAND_R = 7;
const BRAND_G = 94;
const BRAND_B = 84;

function drawHeader(doc: jsPDF, firmName: string, firmTagline: string, firmAddress: string, firmContact: string) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const centerX = pageWidth / 2;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(BRAND_R, BRAND_G, BRAND_B);
  doc.text(firmName, centerX, 18, { align: "center" });

  doc.setFont("helvetica", "bolditalic");
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.text(firmTagline, centerX, 24, { align: "center" });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.text(firmAddress, centerX, 29, { align: "center" });
  doc.text(firmContact, centerX, 33, { align: "center" });

  doc.setDrawColor(BRAND_R, BRAND_G, BRAND_B);
  doc.setLineWidth(0.5);
  doc.line(20, 36, pageWidth - 20, 36);

  doc.setTextColor(0, 0, 0);
}

function drawFooter(doc: jsPDF, pageNum: number, totalPages: number, firmName: string) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const footerY = pageHeight - 12;

  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.line(20, footerY - 4, pageWidth - 20, footerY - 4);

  doc.setFont("helvetica", "italic");
  doc.setFontSize(7);
  doc.setTextColor(160, 160, 160);
  doc.text(`Confidential — ${firmName}`, 20, footerY);
  doc.text("Generated by LegalDesk AI", pageWidth / 2, footerY, { align: "center" });
  doc.text(`Page ${pageNum} of ${totalPages}`, pageWidth - 20, footerY, { align: "right" });
  doc.setTextColor(0, 0, 0);
}

// ── PDF table renderer ──
function drawTable(
  doc: jsPDF,
  headers: string[],
  rows: string[][],
  startY: number,
  margin: number,
  usableWidth: number,
  pageHeight: number,
  bottomMargin: number,
  headerHeight: number,
  brandingStrings: [string, string, string, string]
): number {
  let y = startY;
  const colCount = headers.length;
  const colWidth = usableWidth / colCount;
  const cellPadding = 2;
  const fontSize = 8;
  const headerFontSize = 8;
  const rowHeight = 7;

  // Measure row heights dynamically
  const measureRowHeight = (cells: string[]): number => {
    doc.setFontSize(fontSize);
    let maxH = rowHeight;
    for (let c = 0; c < cells.length; c++) {
      const w = colWidth - cellPadding * 2;
      const wrapped = doc.splitTextToSize(stripMarkdown(cells[c] || ""), w);
      const h = wrapped.length * 4 + cellPadding * 2;
      if (h > maxH) maxH = h;
    }
    return maxH;
  };

  const checkPageBreak = (needed: number) => {
    if (y + needed > pageHeight - bottomMargin) {
      doc.addPage();
      drawHeader(doc, ...brandingStrings);
      y = headerHeight;
    }
  };

  // ── Header row ──
  const hRowH = rowHeight + 2;
  checkPageBreak(hRowH);
  doc.setFillColor(BRAND_R, BRAND_G, BRAND_B);
  doc.rect(margin, y, usableWidth, hRowH, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(headerFontSize);
  doc.setTextColor(255, 255, 255);
  for (let c = 0; c < colCount; c++) {
    const x = margin + c * colWidth + cellPadding;
    doc.text(stripMarkdown(headers[c] || ""), x, y + 5, { maxWidth: colWidth - cellPadding * 2 });
  }
  y += hRowH;

  // ── Data rows ──
  for (let r = 0; r < rows.length; r++) {
    const rh = measureRowHeight(rows[r]);
    checkPageBreak(rh);

    // Alternating row color
    if (r % 2 === 0) {
      doc.setFillColor(245, 245, 245);
      doc.rect(margin, y, usableWidth, rh, "F");
    }

    // Cell borders
    doc.setDrawColor(220, 220, 220);
    doc.setLineWidth(0.2);
    doc.rect(margin, y, usableWidth, rh, "S");
    for (let c = 1; c < colCount; c++) {
      doc.line(margin + c * colWidth, y, margin + c * colWidth, y + rh);
    }

    // Cell text
    doc.setFont("helvetica", "normal");
    doc.setFontSize(fontSize);
    doc.setTextColor(50, 50, 50);
    for (let c = 0; c < rows[r].length; c++) {
      const x = margin + c * colWidth + cellPadding;
      const wrapped = doc.splitTextToSize(stripMarkdown(rows[r][c] || ""), colWidth - cellPadding * 2);
      doc.text(wrapped, x, y + 4);
    }
    y += rh;
  }

  doc.setTextColor(0, 0, 0);
  return y + 3;
}

export function exportAsPdf(content: string, filename: string = "document", profile?: FirmProfile) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const usableWidth = pageWidth - margin * 2;
  const headerHeight = 42;
  const bottomMargin = 22;
  const lineHeight = 5.5;

  const firmName = profile?.firmName?.toUpperCase() ?? DEFAULT_FIRM_NAME;
  const firmTagline = profile?.tagline ?? DEFAULT_FIRM_TAGLINE;
  const firmAddress = profile?.address ?? DEFAULT_FIRM_ADDRESS;
  const firmContact = profile
    ? `Phone: ${profile.phone} | Email: ${profile.email}`
    : DEFAULT_FIRM_CONTACT;
  const brandingStrings: [string, string, string, string] = [firmName, firmTagline, firmAddress, firmContact];

  let y = headerHeight;

  drawHeader(doc, ...brandingStrings);

  // Date
  doc.setFont("helvetica", "italic");
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  const dateStr = `Date: ${new Date().toLocaleDateString("en-IN", {
    day: "2-digit",
    month: "long",
    year: "numeric",
  })}`;
  doc.text(dateStr, pageWidth - margin, y, { align: "right" });
  y += 8;
  doc.setTextColor(0, 0, 0);

  const checkPageBreak = (neededSpace: number) => {
    if (y + neededSpace > pageHeight - bottomMargin) {
      doc.addPage();
      drawHeader(doc, ...brandingStrings);
      y = headerHeight;
    }
  };

  const lines = content.split("\n");
  let i = 0;

  while (i < lines.length) {
    const line = lines[i];

    // ── Table detection ──
    if (line.trim().startsWith("|") && i + 1 < lines.length && lines[i + 1]?.match(/^\|[\s-:|]+\|$/)) {
      const parseCells = (l: string) => l.split("|").slice(1, -1).map((c) => c.trim());
      const headers = parseCells(line);
      i += 2;
      const rows: string[][] = [];
      while (i < lines.length && lines[i].trim().startsWith("|") && !lines[i].match(/^\|[\s-:|]+\|$/)) {
        rows.push(parseCells(lines[i]));
        i++;
      }
      checkPageBreak(20);
      y = drawTable(doc, headers, rows, y, margin, usableWidth, pageHeight, bottomMargin, headerHeight, brandingStrings);
      continue;
    }

    // Skip orphan separator rows
    if (line.match(/^\|[\s-:|]+\|$/)) {
      i++;
      continue;
    }

    // ── Headings ──
    if (line.startsWith("### ")) {
      checkPageBreak(10);
      y += 4;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.setTextColor(50, 50, 50);
      const text = stripMarkdown(line.slice(4));
      const wrapped = doc.splitTextToSize(text, usableWidth);
      doc.text(wrapped, margin, y);
      y += wrapped.length * lineHeight + 1;
      // underline
      doc.setDrawColor(230, 230, 230);
      doc.setLineWidth(0.2);
      doc.line(margin, y, margin + 60, y);
      y += 2;
      doc.setTextColor(0, 0, 0);
      i++;
      continue;
    }
    if (line.startsWith("## ")) {
      checkPageBreak(12);
      y += 5;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(12);
      doc.setTextColor(BRAND_R, BRAND_G, BRAND_B);
      const text = stripMarkdown(line.slice(3));
      const wrapped = doc.splitTextToSize(text, usableWidth);
      doc.text(wrapped, margin, y);
      y += wrapped.length * lineHeight + 1;
      // underline
      doc.setDrawColor(BRAND_R, BRAND_G, BRAND_B);
      doc.setLineWidth(0.3);
      doc.line(margin, y, margin + 80, y);
      y += 3;
      doc.setTextColor(0, 0, 0);
      i++;
      continue;
    }
    if (line.startsWith("# ")) {
      checkPageBreak(14);
      y += 6;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(14);
      doc.setTextColor(BRAND_R, BRAND_G, BRAND_B);
      const text = stripMarkdown(line.slice(2));
      const wrapped = doc.splitTextToSize(text, usableWidth);
      doc.text(wrapped, pageWidth / 2, y, { align: "center", maxWidth: usableWidth });
      y += wrapped.length * (lineHeight + 1) + 3;
      doc.setTextColor(0, 0, 0);
      i++;
      continue;
    }

    // ── Horizontal rule ──
    if (line.match(/^[-*_]{3,}$/)) {
      checkPageBreak(6);
      y += 2;
      doc.setDrawColor(200, 200, 200);
      doc.setLineWidth(0.2);
      doc.line(margin, y, pageWidth - margin, y);
      y += 4;
      i++;
      continue;
    }

    // ── Warning / disclaimer ──
    if (line.includes("⚠️") || (line.startsWith("*") && line.toLowerCase().includes("disclaimer"))) {
      const text = stripMarkdown(line);
      doc.setFontSize(9);
      const wrapped = doc.splitTextToSize(text, usableWidth - 14);
      const boxH = wrapped.length * 4.5 + 6;
      checkPageBreak(boxH + 4);
      // Background
      doc.setFillColor(255, 248, 225);
      doc.setDrawColor(249, 168, 37);
      doc.setLineWidth(0.3);
      doc.roundedRect(margin, y, usableWidth, boxH, 1, 1, "FD");
      // Left accent
      doc.setFillColor(249, 168, 37);
      doc.rect(margin, y, 2, boxH, "F");
      // Text
      doc.setFont("helvetica", "italic");
      doc.setTextColor(121, 85, 72);
      doc.text(wrapped, margin + 6, y + 5);
      y += boxH + 4;
      doc.setTextColor(0, 0, 0);
      i++;
      continue;
    }

    // ── Empty line ──
    if (line.trim() === "") {
      y += 3;
      i++;
      continue;
    }

    // ── Bullet list ──
    if (line.match(/^[\s]*[-•*]\s/)) {
      checkPageBreak(lineHeight + 2);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      const text = stripMarkdown(line.replace(/^[\s]*[-•*]\s/, ""));
      const wrapped = doc.splitTextToSize(text, usableWidth - 8);
      doc.setFillColor(BRAND_R, BRAND_G, BRAND_B);
      doc.circle(margin + 2, y - 1, 0.8, "F");
      doc.text(wrapped, margin + 7, y);
      y += wrapped.length * lineHeight;
      i++;
      continue;
    }

    // ── Numbered list ──
    const numMatch = line.match(/^[\s]*(\d+)[.)]\s/);
    if (numMatch) {
      checkPageBreak(lineHeight + 2);
      const text = stripMarkdown(line.replace(/^[\s]*\d+[.)]\s/, ""));
      const wrapped = doc.splitTextToSize(text, usableWidth - 10);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(BRAND_R, BRAND_G, BRAND_B);
      doc.text(`${numMatch[1]}.`, margin + 2, y);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(50, 50, 50);
      doc.text(wrapped, margin + 10, y);
      y += wrapped.length * lineHeight;
      doc.setTextColor(0, 0, 0);
      i++;
      continue;
    }

    // ── Regular text ──
    const isBoldLine = line.startsWith("**") && line.endsWith("**");
    if (isBoldLine) {
      doc.setFont("helvetica", "bold");
    } else {
      doc.setFont("helvetica", "normal");
    }
    doc.setFontSize(10);
    doc.setTextColor(50, 50, 50);
    const text = stripMarkdown(line);
    const wrapped = doc.splitTextToSize(text, usableWidth);
    checkPageBreak(wrapped.length * lineHeight);
    doc.text(wrapped, margin, y);
    y += wrapped.length * lineHeight;
    doc.setTextColor(0, 0, 0);
    i++;
  }

  // Draw footers on all pages
  const totalPages = doc.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    drawFooter(doc, p, totalPages, profile?.firmName ?? "Nair & Associates");
  }

  doc.save(`${filename}.pdf`);
}

function stripMarkdown(text: string): string {
  return text
    .replace(/\*\*\*(.+?)\*\*\*/g, "$1")
    .replace(/\*\*(.+?)\*\*/g, "$1")
    .replace(/\*(.+?)\*/g, "$1")
    .replace(/`(.+?)`/g, "$1");
}
